//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractWorkerView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Sex { get; set; }
        public string Specialization { get; set; }
    }
}
