//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databaseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_worker_Info
    {
        public int Employee_Id { get; set; }
        public string name { get; set; }
        public string Specialization { get; set; }
        public int Contract_id { get; set; }
        public int Project_id { get; set; }
    }
}
